// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostUserReader is a Reader for the PostUser structure.
type PostUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 202:
		result := NewPostUserAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostUserAccepted creates a PostUserAccepted with default headers values
func NewPostUserAccepted() *PostUserAccepted {
	return &PostUserAccepted{}
}

/*PostUserAccepted handles this case with default header values.

Successful
*/
type PostUserAccepted struct {
}

func (o *PostUserAccepted) Error() string {
	return fmt.Sprintf("[POST /user][%d] postUserAccepted ", 202)
}

func (o *PostUserAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
