// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/crioto/swagger-playground/models"
)

// NewPutUserUsernameParams creates a new PutUserUsernameParams object
// with the default values initialized.
func NewPutUserUsernameParams() *PutUserUsernameParams {
	var ()
	return &PutUserUsernameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutUserUsernameParamsWithTimeout creates a new PutUserUsernameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutUserUsernameParamsWithTimeout(timeout time.Duration) *PutUserUsernameParams {
	var ()
	return &PutUserUsernameParams{

		timeout: timeout,
	}
}

// NewPutUserUsernameParamsWithContext creates a new PutUserUsernameParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutUserUsernameParamsWithContext(ctx context.Context) *PutUserUsernameParams {
	var ()
	return &PutUserUsernameParams{

		Context: ctx,
	}
}

// NewPutUserUsernameParamsWithHTTPClient creates a new PutUserUsernameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutUserUsernameParamsWithHTTPClient(client *http.Client) *PutUserUsernameParams {
	var ()
	return &PutUserUsernameParams{
		HTTPClient: client,
	}
}

/*PutUserUsernameParams contains all the parameters to send to the API endpoint
for the put user username operation typically these are written to a http.Request
*/
type PutUserUsernameParams struct {

	/*UserSParameters
	  Updated user object

	*/
	UserSParameters *models.User
	/*Username*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put user username params
func (o *PutUserUsernameParams) WithTimeout(timeout time.Duration) *PutUserUsernameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put user username params
func (o *PutUserUsernameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put user username params
func (o *PutUserUsernameParams) WithContext(ctx context.Context) *PutUserUsernameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put user username params
func (o *PutUserUsernameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put user username params
func (o *PutUserUsernameParams) WithHTTPClient(client *http.Client) *PutUserUsernameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put user username params
func (o *PutUserUsernameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserSParameters adds the userSParameters to the put user username params
func (o *PutUserUsernameParams) WithUserSParameters(userSParameters *models.User) *PutUserUsernameParams {
	o.SetUserSParameters(userSParameters)
	return o
}

// SetUserSParameters adds the userSParameters to the put user username params
func (o *PutUserUsernameParams) SetUserSParameters(userSParameters *models.User) {
	o.UserSParameters = userSParameters
}

// WithUsername adds the username to the put user username params
func (o *PutUserUsernameParams) WithUsername(username string) *PutUserUsernameParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the put user username params
func (o *PutUserUsernameParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *PutUserUsernameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.UserSParameters != nil {
		if err := r.SetBodyParam(o.UserSParameters); err != nil {
			return err
		}
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
