// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Example API
This is example API documentation


    Schemes:
      https
    Host: example.api.com
    BasePath: /v2
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
