// Code generated by go-swagger; DO NOT EDIT.

package cars

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetCarsIDOKCode is the HTTP code returned for type GetCarsIDOK
const GetCarsIDOKCode int = 200

/*GetCarsIDOK Successful

swagger:response getCarsIdOK
*/
type GetCarsIDOK struct {
}

// NewGetCarsIDOK creates GetCarsIDOK with default headers values
func NewGetCarsIDOK() *GetCarsIDOK {
	return &GetCarsIDOK{}
}

// WriteResponse to the client
func (o *GetCarsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetCarsIDBadRequestCode is the HTTP code returned for type GetCarsIDBadRequest
const GetCarsIDBadRequestCode int = 400

/*GetCarsIDBadRequest Invalid input

swagger:response getCarsIdBadRequest
*/
type GetCarsIDBadRequest struct {
}

// NewGetCarsIDBadRequest creates GetCarsIDBadRequest with default headers values
func NewGetCarsIDBadRequest() *GetCarsIDBadRequest {
	return &GetCarsIDBadRequest{}
}

// WriteResponse to the client
func (o *GetCarsIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetCarsIDNotFoundCode is the HTTP code returned for type GetCarsIDNotFound
const GetCarsIDNotFoundCode int = 404

/*GetCarsIDNotFound Car not found

swagger:response getCarsIdNotFound
*/
type GetCarsIDNotFound struct {
}

// NewGetCarsIDNotFound creates GetCarsIDNotFound with default headers values
func NewGetCarsIDNotFound() *GetCarsIDNotFound {
	return &GetCarsIDNotFound{}
}

// WriteResponse to the client
func (o *GetCarsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
