// Code generated by go-swagger; DO NOT EDIT.

package cars

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCarsIDHandlerFunc turns a function with the right signature into a get cars ID handler
type GetCarsIDHandlerFunc func(GetCarsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCarsIDHandlerFunc) Handle(params GetCarsIDParams) middleware.Responder {
	return fn(params)
}

// GetCarsIDHandler interface for that can handle valid get cars ID params
type GetCarsIDHandler interface {
	Handle(GetCarsIDParams) middleware.Responder
}

// NewGetCarsID creates a new http.Handler for the get cars ID operation
func NewGetCarsID(ctx *middleware.Context, handler GetCarsIDHandler) *GetCarsID {
	return &GetCarsID{Context: ctx, Handler: handler}
}

/*GetCarsID swagger:route GET /cars/{id} cars getCarsId

get car by id

*/
type GetCarsID struct {
	Context *middleware.Context
	Handler GetCarsIDHandler
}

func (o *GetCarsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCarsIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
