// Code generated by go-swagger; DO NOT EDIT.

package cars

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostCarsOKCode is the HTTP code returned for type PostCarsOK
const PostCarsOKCode int = 200

/*PostCarsOK Successful

swagger:response postCarsOK
*/
type PostCarsOK struct {
}

// NewPostCarsOK creates PostCarsOK with default headers values
func NewPostCarsOK() *PostCarsOK {
	return &PostCarsOK{}
}

// WriteResponse to the client
func (o *PostCarsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostCarsMethodNotAllowedCode is the HTTP code returned for type PostCarsMethodNotAllowed
const PostCarsMethodNotAllowedCode int = 405

/*PostCarsMethodNotAllowed Error in adding car

swagger:response postCarsMethodNotAllowed
*/
type PostCarsMethodNotAllowed struct {
}

// NewPostCarsMethodNotAllowed creates PostCarsMethodNotAllowed with default headers values
func NewPostCarsMethodNotAllowed() *PostCarsMethodNotAllowed {
	return &PostCarsMethodNotAllowed{}
}

// WriteResponse to the client
func (o *PostCarsMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
