// Code generated by go-swagger; DO NOT EDIT.

package cars

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/crioto/swagger-playground/models"
)

// NewPostCarsParams creates a new PostCarsParams object
// with the default values initialized.
func NewPostCarsParams() PostCarsParams {
	var ()
	return PostCarsParams{}
}

// PostCarsParams contains all the bound params for the post cars operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostCars
type PostCarsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*add a new car
	  Required: true
	  In: body
	*/
	CarSParameters *models.Cars
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostCarsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Cars
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("carSParameters", "body"))
			} else {
				res = append(res, errors.NewParseError("carSParameters", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.CarSParameters = &body
			}
		}

	} else {
		res = append(res, errors.Required("carSParameters", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
