// Code generated by go-swagger; DO NOT EDIT.

package cars

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostCarsHandlerFunc turns a function with the right signature into a post cars handler
type PostCarsHandlerFunc func(PostCarsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCarsHandlerFunc) Handle(params PostCarsParams) middleware.Responder {
	return fn(params)
}

// PostCarsHandler interface for that can handle valid post cars params
type PostCarsHandler interface {
	Handle(PostCarsParams) middleware.Responder
}

// NewPostCars creates a new http.Handler for the post cars operation
func NewPostCars(ctx *middleware.Context, handler PostCarsHandler) *PostCars {
	return &PostCars{Context: ctx, Handler: handler}
}

/*PostCars swagger:route POST /cars cars postCars

Add car

*/
type PostCars struct {
	Context *middleware.Context
	Handler PostCarsHandler
}

func (o *PostCars) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostCarsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
