// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteUserUsernameOKCode is the HTTP code returned for type DeleteUserUsernameOK
const DeleteUserUsernameOKCode int = 200

/*DeleteUserUsernameOK Successful

swagger:response deleteUserUsernameOK
*/
type DeleteUserUsernameOK struct {
}

// NewDeleteUserUsernameOK creates DeleteUserUsernameOK with default headers values
func NewDeleteUserUsernameOK() *DeleteUserUsernameOK {
	return &DeleteUserUsernameOK{}
}

// WriteResponse to the client
func (o *DeleteUserUsernameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteUserUsernameBadRequestCode is the HTTP code returned for type DeleteUserUsernameBadRequest
const DeleteUserUsernameBadRequestCode int = 400

/*DeleteUserUsernameBadRequest Invalid username

swagger:response deleteUserUsernameBadRequest
*/
type DeleteUserUsernameBadRequest struct {
}

// NewDeleteUserUsernameBadRequest creates DeleteUserUsernameBadRequest with default headers values
func NewDeleteUserUsernameBadRequest() *DeleteUserUsernameBadRequest {
	return &DeleteUserUsernameBadRequest{}
}

// WriteResponse to the client
func (o *DeleteUserUsernameBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteUserUsernameNotFoundCode is the HTTP code returned for type DeleteUserUsernameNotFound
const DeleteUserUsernameNotFoundCode int = 404

/*DeleteUserUsernameNotFound User not found

swagger:response deleteUserUsernameNotFound
*/
type DeleteUserUsernameNotFound struct {
}

// NewDeleteUserUsernameNotFound creates DeleteUserUsernameNotFound with default headers values
func NewDeleteUserUsernameNotFound() *DeleteUserUsernameNotFound {
	return &DeleteUserUsernameNotFound{}
}

// WriteResponse to the client
func (o *DeleteUserUsernameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
