// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUserUsernameHandlerFunc turns a function with the right signature into a get user username handler
type GetUserUsernameHandlerFunc func(GetUserUsernameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserUsernameHandlerFunc) Handle(params GetUserUsernameParams) middleware.Responder {
	return fn(params)
}

// GetUserUsernameHandler interface for that can handle valid get user username params
type GetUserUsernameHandler interface {
	Handle(GetUserUsernameParams) middleware.Responder
}

// NewGetUserUsername creates a new http.Handler for the get user username operation
func NewGetUserUsername(ctx *middleware.Context, handler GetUserUsernameHandler) *GetUserUsername {
	return &GetUserUsername{Context: ctx, Handler: handler}
}

/*GetUserUsername swagger:route GET /user/{username} user getUserUsername

Get user by user name

*/
type GetUserUsername struct {
	Context *middleware.Context
	Handler GetUserUsernameHandler
}

func (o *GetUserUsername) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserUsernameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
