// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUserAcceptedCode is the HTTP code returned for type PostUserAccepted
const PostUserAcceptedCode int = 202

/*PostUserAccepted Successful

swagger:response postUserAccepted
*/
type PostUserAccepted struct {
}

// NewPostUserAccepted creates PostUserAccepted with default headers values
func NewPostUserAccepted() *PostUserAccepted {
	return &PostUserAccepted{}
}

// WriteResponse to the client
func (o *PostUserAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(202)
}
