// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutUserUsernameOKCode is the HTTP code returned for type PutUserUsernameOK
const PutUserUsernameOKCode int = 200

/*PutUserUsernameOK Successful

swagger:response putUserUsernameOK
*/
type PutUserUsernameOK struct {
}

// NewPutUserUsernameOK creates PutUserUsernameOK with default headers values
func NewPutUserUsernameOK() *PutUserUsernameOK {
	return &PutUserUsernameOK{}
}

// WriteResponse to the client
func (o *PutUserUsernameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutUserUsernameBadRequestCode is the HTTP code returned for type PutUserUsernameBadRequest
const PutUserUsernameBadRequestCode int = 400

/*PutUserUsernameBadRequest Invalid user

swagger:response putUserUsernameBadRequest
*/
type PutUserUsernameBadRequest struct {
}

// NewPutUserUsernameBadRequest creates PutUserUsernameBadRequest with default headers values
func NewPutUserUsernameBadRequest() *PutUserUsernameBadRequest {
	return &PutUserUsernameBadRequest{}
}

// WriteResponse to the client
func (o *PutUserUsernameBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PutUserUsernameNotFoundCode is the HTTP code returned for type PutUserUsernameNotFound
const PutUserUsernameNotFoundCode int = 404

/*PutUserUsernameNotFound User not found

swagger:response putUserUsernameNotFound
*/
type PutUserUsernameNotFound struct {
}

// NewPutUserUsernameNotFound creates PutUserUsernameNotFound with default headers values
func NewPutUserUsernameNotFound() *PutUserUsernameNotFound {
	return &PutUserUsernameNotFound{}
}

// WriteResponse to the client
func (o *PutUserUsernameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
