// Code generated by go-swagger; DO NOT EDIT.

package cars

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetCarsIDReader is a Reader for the GetCarsID structure.
type GetCarsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCarsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCarsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetCarsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetCarsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCarsIDOK creates a GetCarsIDOK with default headers values
func NewGetCarsIDOK() *GetCarsIDOK {
	return &GetCarsIDOK{}
}

/*GetCarsIDOK handles this case with default header values.

Successful
*/
type GetCarsIDOK struct {
}

func (o *GetCarsIDOK) Error() string {
	return fmt.Sprintf("[GET /cars/{id}][%d] getCarsIdOK ", 200)
}

func (o *GetCarsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetCarsIDBadRequest creates a GetCarsIDBadRequest with default headers values
func NewGetCarsIDBadRequest() *GetCarsIDBadRequest {
	return &GetCarsIDBadRequest{}
}

/*GetCarsIDBadRequest handles this case with default header values.

Invalid input
*/
type GetCarsIDBadRequest struct {
}

func (o *GetCarsIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /cars/{id}][%d] getCarsIdBadRequest ", 400)
}

func (o *GetCarsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetCarsIDNotFound creates a GetCarsIDNotFound with default headers values
func NewGetCarsIDNotFound() *GetCarsIDNotFound {
	return &GetCarsIDNotFound{}
}

/*GetCarsIDNotFound handles this case with default header values.

Car not found
*/
type GetCarsIDNotFound struct {
}

func (o *GetCarsIDNotFound) Error() string {
	return fmt.Sprintf("[GET /cars/{id}][%d] getCarsIdNotFound ", 404)
}

func (o *GetCarsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
