// Code generated by go-swagger; DO NOT EDIT.

package cars

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCarsIDParams creates a new GetCarsIDParams object
// with the default values initialized.
func NewGetCarsIDParams() *GetCarsIDParams {
	var ()
	return &GetCarsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCarsIDParamsWithTimeout creates a new GetCarsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCarsIDParamsWithTimeout(timeout time.Duration) *GetCarsIDParams {
	var ()
	return &GetCarsIDParams{

		timeout: timeout,
	}
}

// NewGetCarsIDParamsWithContext creates a new GetCarsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCarsIDParamsWithContext(ctx context.Context) *GetCarsIDParams {
	var ()
	return &GetCarsIDParams{

		Context: ctx,
	}
}

// NewGetCarsIDParamsWithHTTPClient creates a new GetCarsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCarsIDParamsWithHTTPClient(client *http.Client) *GetCarsIDParams {
	var ()
	return &GetCarsIDParams{
		HTTPClient: client,
	}
}

/*GetCarsIDParams contains all the parameters to send to the API endpoint
for the get cars ID operation typically these are written to a http.Request
*/
type GetCarsIDParams struct {

	/*ID
	  id of car

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cars ID params
func (o *GetCarsIDParams) WithTimeout(timeout time.Duration) *GetCarsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cars ID params
func (o *GetCarsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cars ID params
func (o *GetCarsIDParams) WithContext(ctx context.Context) *GetCarsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cars ID params
func (o *GetCarsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cars ID params
func (o *GetCarsIDParams) WithHTTPClient(client *http.Client) *GetCarsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cars ID params
func (o *GetCarsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get cars ID params
func (o *GetCarsIDParams) WithID(id int64) *GetCarsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get cars ID params
func (o *GetCarsIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCarsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
