// Code generated by go-swagger; DO NOT EDIT.

package cars

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/crioto/swagger-playground/models"
)

// NewPostCarsParams creates a new PostCarsParams object
// with the default values initialized.
func NewPostCarsParams() *PostCarsParams {
	var ()
	return &PostCarsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostCarsParamsWithTimeout creates a new PostCarsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostCarsParamsWithTimeout(timeout time.Duration) *PostCarsParams {
	var ()
	return &PostCarsParams{

		timeout: timeout,
	}
}

// NewPostCarsParamsWithContext creates a new PostCarsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostCarsParamsWithContext(ctx context.Context) *PostCarsParams {
	var ()
	return &PostCarsParams{

		Context: ctx,
	}
}

// NewPostCarsParamsWithHTTPClient creates a new PostCarsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostCarsParamsWithHTTPClient(client *http.Client) *PostCarsParams {
	var ()
	return &PostCarsParams{
		HTTPClient: client,
	}
}

/*PostCarsParams contains all the parameters to send to the API endpoint
for the post cars operation typically these are written to a http.Request
*/
type PostCarsParams struct {

	/*CarSParameters
	  add a new car

	*/
	CarSParameters *models.Cars

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post cars params
func (o *PostCarsParams) WithTimeout(timeout time.Duration) *PostCarsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post cars params
func (o *PostCarsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post cars params
func (o *PostCarsParams) WithContext(ctx context.Context) *PostCarsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post cars params
func (o *PostCarsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post cars params
func (o *PostCarsParams) WithHTTPClient(client *http.Client) *PostCarsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post cars params
func (o *PostCarsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCarSParameters adds the carSParameters to the post cars params
func (o *PostCarsParams) WithCarSParameters(carSParameters *models.Cars) *PostCarsParams {
	o.SetCarSParameters(carSParameters)
	return o
}

// SetCarSParameters adds the carSParameters to the post cars params
func (o *PostCarsParams) SetCarSParameters(carSParameters *models.Cars) {
	o.CarSParameters = carSParameters
}

// WriteToRequest writes these params to a swagger request
func (o *PostCarsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CarSParameters != nil {
		if err := r.SetBodyParam(o.CarSParameters); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
